name: NoCommunication
version: 1.0
main: me.JangMoobin.nocommunication.NoCommunication
api-version: 1.20
commands:
  nocomm:
    description: Toggle or reload the NoCommunication plugin.
    usage: /nocomm <toggle|reload>
    permission: op
